version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: pedidos
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on: [db]
    ports: ["8080:8080"]

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=/api
    depends_on: [backend]
    ports: ["5173:80"]   # Nginx sirve en 80, pero lo exponemos en 5173
    # Para que /api vaya al backend en local, accede a http://localhost:8080/api desde el front
    # (en compose simple, abrirás el front en http://localhost:5173 y el back en :8080)

volumes:
  dbdata:
